### ISSUE TITLE
High CPU and network usage

### ISSUE THREAD

**Issue by NoverNobida** [immanuelfodor/matrix-encrypted-webhooks#3]
This program can cause high CPU (100%) and network (≈1MB/s⬆⬇) usage. When I stop the program, the CPU usage drops to normal, and there is no network usage.
![图片](https://user-images.githubusercontent.com/46912250/147634914-a2aee96a-01be-411f-9616-8df48ec20dea.png)
⬇
![图片](https://user-images.githubusercontent.com/46912250/147635018-55fabef8-5427-4ab4-b0b1-08b1e7b7f241.png)

**Comment by immanuelfodor** [comment]
Hi, could you please provide more context, in what cases do you observe this behavior? The only thing I can think of is when the Matrix server is unavailable/down/restarting.

**Comment by NoverNobida** [comment]
I found the reason. Because I have changed the account before, although the ID and password have not been changed, those authorization files has actually been changed. I didn't delete the folder `config` created by docker-compose
( 
```
volumes:
    - ./config:/config
```
)
causing the program to run incorrectly.
